In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium

In [2]:
#load CSV file - ignore header
df = pd.read_csv('../data/POWER_Point_Monthly_Timeseries_1990_2020_035d6118N_083d4895W_LST_GSMNP.csv',header=None)
#print("Column Names:", data.columns)
#df.head(10)

In [9]:
#extract lat and lon, pick index 3,0 to get the values - revisit and remove the junk rows
location_row = df.iloc[3,0]
latitude_str = location_row.split('Latitude')[1].split('Longitude')[0].strip()
longitude_str = location_row.split('Longitude')[1].strip()
#convert to float
latitude = float(latitude_str)
longitude = float(longitude_str)

print('Latitude:', latitude)
print('Longitude', longitude)

Latitude: 35.6118
Longitude -83.4895

In [3]:
df.head(50)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,-BEGIN HEADER-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NASA/POWER CERES/MERRA2 Native Resolution Mont...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dates (month/day/year): 01/01/1990 through 12/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Location: Latitude 35.6118 Longitude -83.4895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Elevation from MERRA-2: Average for 0.5 x 0.62...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,The value for missing source data that cannot ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Parameter(s):,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,T2M MERRA-2 Temperature at 2 M...,Average Air temp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,RH2M MERRA-2 Relative Humidity ...,Relative Humidity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,T2M_MAX MERRA-2 Temperature at 2 M...,MAX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,T2M_MIN MERRA-2 Temperature at 2 M...,MIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PRECTOTCORR MERRA-2 Precipitation Corr...,Precipitation Corrected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,PRECTOTCORR_SUM MERRA-2 Precipitation Corr...,Precipitation Corrected_SUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,-END HEADER-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
15,T2M,1990,3.46,6.23,8.61,10.67,16.01,20.44,22.21,23.04,19.74,12.92,8.35,5.3,13.12
16,T2M,1991,2.44,3.88,7.8,13.57,19.05,20.48,22.93,21.4,18.96,12.88,5.39,4.23,12.8
17,T2M,1992,1.62,5.04,6.16,11.3,14.99,18.99,22.51,20.64,18.82,11.65,6.96,2.12,11.75
18,T2M,1993,3.62,1.28,4.62,9.94,16.53,21.09,25.83,23.48,19.44,12.58,6.84,1.35,12.29
19,T2M,1994,-1.89,3.69,6.85,13.52,14.68,21.48,21.54,21.19,17.66,12.6,9.25,4.69,12.14
20,T2M,1995,2.06,1.52,8.56,12.53,17.02,19.94,24.18,24.51,18.94,12.8,4.33,0.37,12.3
21,T2M,1996,-0.35,1.24,3.93,10.13,17.74,20.64,21.67,21.83,17.97,12.69,4.73,3.97,11.38
22,T2M,1997,1.11,5.06,9.74,9.6,14.32,19,23.05,21.62,19.74,12.85,4.55,1.94,11.92
23,T2M,1998,3.44,3.61,5.86,11.71,18.6,21.72,22.79,22.9,22.21,15.06,9.08,4.94,13.55
24,T2M,1999,3.65,4.32,4.19,13.67,16.23,20.24,23.4,23.12,19.33,12.87,9.36,3.37,12.85
25,T2M,2000,1.1,4.45,9.16,10.78,17.73,20.98,22.55,22.44,18.95,14.48,6.03,-1.61,12.27
26,T2M,2001,0.1,5.3,4.7,13.32,16.91,19.82,22.5,21.96,17.4,11.64,10.55,5.25,12.48
27,T2M,2002,2.9,2.67,7.73,13.69,16.01,21.23,23.83,23.69,20.88,14.84,5.68,1.45,12.94
28,T2M,2003,-1.26,2.82,9.01,12.89,17.08,19.29,21.68,22.62,17.9,12.37,10.01,1.02,12.16
29,T2M,2004,0.81,2.14,8.98,11.78,18.73,20.83,22.47,21.11,18.62,14.99,9.46,2.4,12.73
30,T2M,2005,3.69,3.96,5.75,11.87,15.24,20.65,23.06,23.4,20.65,13.95,8.61,0.25,12.63
31,T2M,2006,4.87,1.57,7.06,14.39,16.25,20.51,23.45,24.37,17.41,11.29,7.13,5.1,12.85
32,T2M,2007,2.9,0.48,10.32,10.38,18.01,22.3,22.08,25.87,21.07,15.75,6.97,5.8,13.58
33,T2M,2008,0.8,4.37,7.48,12.2,16.01,22.33,22.9,22.56,19.62,12.83,5.57,4.3,12.6
34,T2M,2009,0.83,2.56,8.14,11.8,16.87,21.62,20.34,21.4,18.98,12.13,8.25,1.14,12.05
35,T2M,2010,-1.5,-1.55,5.69,13.92,18.51,23.1,24.52,24.54,20.48,12.91,7.87,-2.51,12.23
36,T2M,2011,-0.81,4.21,8.06,13.71,16.8,22.29,24.5,23.69,18.73,11.62,8.45,5.19,13.08
37,T2M,2012,3.72,5.23,12.53,13.52,18.67,20.89,24.42,21.92,18.51,11.82,6.01,5.38,13.58
38,T2M,2013,3.83,1.91,3.33,11.69,15.71,20.58,21.47,21.11,18.62,13.28,4.81,4.06,11.76
39,T2M,2014,-2.48,2.57,5.96,12.55,17.27,21.44,21.07,21.9,19.88,13.44,3.67,4.65,11.87
40,T2M,2015,0.82,-1.76,8.21,13.33,18.08,22.2,22.52,21.33,19.6,13.32,9.84,9.77,13.19
41,T2M,2016,-0.2,2.96,10.13,12.61,16.21,22.45,24.8,24.48,22.26,16.33,10.06,3.67,13.84
42,T2M,2017,5.72,7.21,7.88,14.94,17.02,20.42,23.25,21.77,18.56,14.42,8.14,2.85,13.55
43,T2M,2018,-0.99,8.43,6.17,9.83,19.48,22.05,22.88,22.3,21.94,14.17,5.61,3.88,13
44,T2M,2019,2.07,7.06,6.35,13.71,19.31,20.56,23.05,23.26,23.5,16.2,5.45,5.79,13.9
45,T2M,2020,4.42,4.75,10.84,11.05,15.3,20.27,23.83,22.63,18.9,14.5,9.47,2.53,13.23
46,RH2M,1990,87.94,84.69,84.5,78.25,80.06,77.69,75.38,69.5,68.88,76.12,78.06,83.94,78.75
47,RH2M,1991,88.19,81.38,82.44,81.5,82.44,82.5,81.38,81.31,75.88,72.06,74.81,83.56,80.62
48,RH2M,1992,84.5,80.81,80.06,79.25,79.94,82.19,79.31,77.94,81.31,75.88,82.06,87.12,80.88
49,RH2M,1993,85.81,81.62,83.88,77.38,79.94,76.38,63.19,69.62,69.31,69.81,76.06,85.31,76.5

In [8]:
# THIS DOESNT WORK YET
#convert celcius to farenheit in the months columns but ignore RH2M
months_columns = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']
temperature_parameters = ['T2M', 'T2M_MAX', 'T2M_MIN']

# Iterate over the columns and convert Celsius to Fahrenheit for specific parameters
for column in months_columns:
    parameter = df.at[14, column]  # Get the parameter value from the 'PARAMETER' row
    if parameter in temperature_parameters:
        df[column] = (df[column] * 9/5) + 32

print(type(df))

KeyError: 'JAN'